[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "protogo"
version = "0.1.0"
authors = [
    { name="Artur Jaroszewicz", email="arturtjaro@gmail.com" },
]
dependencies = [
    # your package dependencies here
]